### PR TITLE
Iam changes deploying on cloud

### PR DESCRIPTION
**Pull request by dalmago**
Supporting IAM authentication while deploying on cloud

### CODE REVIEW

**Comment by sanjeevghimire** [comment]
@dalmago just that fix won't fix the IAM issue. The way the token was used before has to changed too.  I have changes that fixes all of these in earlier PR #22 . You can check it out.

**Comment by dalmago** [comment]
I've seen PR #22, but those just change when running the application locally. Don't you have to change also inside the `if 'VCAP_SERVICES' in os.environ:`? 

Besides, this PR is to the branch `iam-changes`, which also includes PR #22 already.

**Comment by dolph** [comment]
I merged #22 and deleted the base branch there, which apparently deleted the branch here as a side-effect. @sanjeevghimire didn't see your last message. Going to try to revive this!

**Comment by sanjeevghimire** [comment]
@dalmago LGTM and merging. I didn't realize this was for vcap when pushing to ibm cloud

**Pull request merged**
